// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIuU1-UXeIppHsfH_bzm0S0liQ16sZuvg',
    appId: '1:474434041550:web:d6b5db189d421b0b6dc29f',
    messagingSenderId: '474434041550',
    projectId: 'hirun-6176b',
    authDomain: 'hirun-6176b.firebaseapp.com',
    storageBucket: 'hirun-6176b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPDyYybQQELZcGxEny13QBgc5wtytAQ0',
    appId: '1:474434041550:android:a4ffd038c878635a6dc29f',
    messagingSenderId: '474434041550',
    projectId: 'hirun-6176b',
    storageBucket: 'hirun-6176b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD35IDGzSIygWju-IWTdHOsLmt1EfMnsc4',
    appId: '1:474434041550:ios:95ed078de8ad6de16dc29f',
    messagingSenderId: '474434041550',
    projectId: 'hirun-6176b',
    storageBucket: 'hirun-6176b.appspot.com',
    iosClientId:
        '474434041550-gn648capmc4kp4les142ffmormjt3gj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD35IDGzSIygWju-IWTdHOsLmt1EfMnsc4',
    appId: '1:474434041550:ios:d8b8c4e2351c6e3c6dc29f',
    messagingSenderId: '474434041550',
    projectId: 'hirun-6176b',
    storageBucket: 'hirun-6176b.appspot.com',
    iosClientId:
        '474434041550-0te41rr02s6v1680s0vn2fun853ghc44.apps.googleusercontent.com',
    iosBundleId: 'com.example.bn.RunnerTests',
  );
}
